//
// Not autogenerated, actions on events and for values in UI
//

#include <Arduino.h>

#include "ui/actions.h"
#include "ui/ui.h"
#include "ui/vars.h"

#include "main.h"
#include "turn_wifi.h"
#include "turning.h"
#include "turn_tft.h"


extern void action_button_press(lv_event_t * e) {
  // Action on button click
  if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
    const int ud = (const int )lv_event_get_user_data(e);
#ifdef DEBUG2
    Serial.printf("Button prog clicked: %d\n", ud);
#endif //DEBUG2
    switch (ud) {
      case 1:
        toggle_stop();
        break;
      case 2:
        toggle_face(false);
        break;
    }
  }
}

extern void action_button_press_config(lv_event_t * e) {
  // Action on config button click
  if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
    const int ud = (const int )lv_event_get_user_data(e);
#ifdef DEBUG2
    Serial.printf("Config button clicked: %d\n", ud);
#endif //DEBUG2
    switch (ud) {
      case 1:
        // Reset wifi config
        // TODO popup here saying wifi is disabled when it is
#ifdef TURN_WIFI_ENABLE
        Serial.println("Resetting WiFi config");
        resetWifi();
        delay(1000);
        ESP.restart();
#endif //TURN_WIFI_ENABLE
        break;
      case 2:
        // Reset admin password
        // TODO popup here saying wifi is disabled when it is
#ifdef TURN_WIFI_ENABLE
        Serial.println("Clearing WiFi admin password");
        clearAdminPW();
#endif //TURN_WIFI_ENABLE
        // Add a popup here saying this has been done
        break;
      case 3:
#ifdef DEBUG
        Serial.println("Loading signal strength screen");
#endif //DEBUG
        // Switch to ZPT signal strength screen
        loadScreen(SCREEN_ID_ZPT_SIGNAL);
        break;
      case 4:
        // TODO enable switching back to main mode?
        // Reboot
        ESP.restart();
        break;
      case 5:
#ifdef DEBUG
        Serial.println("Loading config main screen");
#endif //DEBUG
        // Switch back from ZPT signal strength to main config
        loadScreen(SCREEN_ID_CONFIG_MAIN);
        break;
    }
  }
}

void action_list_select(lv_event_t *e) {
  // Selection changed in UI
  if (lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) {
    const int ud = (const int )lv_event_get_user_data(e);
#ifdef DEBUG
    Serial.printf("List selected: %d\n", ud);
#endif //DEBUG
    // These get selections direct from lv_ because EEZ has not caught up yet
    switch (ud) {
      case 1:
        // program list selection
#ifdef DEBUG2
        Serial.println("Program selection made");
#endif //DEBUG2
        changeprognum(lv_dropdown_get_selected(lv_event_get_target(e)));
        break;
      case 2:
        // Stage selection
#ifdef DEBUG2
        Serial.println("Stage selection made");
#endif //DEBUG2
        changestagenum(lv_dropdown_get_selected(lv_event_get_target(e)), false, false);
        break;
    }
  }
}

void action_dropdown_checked(lv_event_t *e) {
  // Dropdown opened
  if (lv_event_get_code(e) == LV_EVENT_READY) {
    const int ud = (const int )lv_event_get_user_data(e);
#ifdef DEBUG2
    Serial.printf("Dropdown opened prog: %d\n", ud);
#endif //DEBUG2
    // Any dropdown that is opened, set the list font other than default
    //lv_obj_set_style_text_font(lv_dropdown_get_list(lv_event_get_target(e)), &lv_font_montserrat_16, 0);

    // When a dropdown is opened make sure the other one closes
    switch (ud) {
      case 1:
        // When you open the programs dropdown, close the stage dropdown
        lv_dropdown_close(objects.stage_dropdown);
        break;
      case 2:
        // When you open the stage dropdown, close the programs dropdown
        lv_dropdown_close(objects.prog_dropdown);
        break;
    }
  }
}

void action_table_row_draw(lv_event_t *e) {
  lv_obj_t * obj = lv_event_get_target(e);
  lv_obj_draw_part_dsc_t * dsc = lv_event_get_draw_part_dsc(e);

  // If the cells are being drawn
  if (dsc->part == LV_PART_ITEMS) {
    uint32_t row = dsc->id /  lv_table_get_col_cnt(obj);
    //uint32_t col = dsc->id - row * lv_table_get_col_cnt(obj);

    // row colours
    switch (row) {
      case PC_R_H1:
        dsc->rect_dsc->bg_color=lv_color_hex(0x0c2070);
        dsc->label_dsc->align = LV_TEXT_ALIGN_AUTO;
        break;
      case PC_R_D1:
      case PC_R_S1:
        dsc->label_dsc->align = LV_TEXT_ALIGN_AUTO;
      //  dsc->rect_dsc->bg_color=lv_color_hex(0x111111);
        break;
    }
  }
}
