//
// Not autogenerated, variables in UI
//

#include <Arduino.h>

#include "ui/vars.h"


int32_t zpt_signal_strength_int;

int32_t get_var_zpt_signal_strength_int() {
    return zpt_signal_strength_int;
}

void set_var_zpt_signal_strength_int(int32_t value) {
    zpt_signal_strength_int = value;
}


bool prog_face_bar_checked_bool;

bool get_var_prog_face_bar_checked_bool() {
    return prog_face_bar_checked_bool;
}

void set_var_prog_face_bar_checked_bool(bool value) {
    prog_face_bar_checked_bool = value;
}


int32_t prog_face_bar_int;

int32_t get_var_prog_face_bar_int() {
    return prog_face_bar_int;
}

void set_var_prog_face_bar_int(int32_t value) {
    prog_face_bar_int = value;
}


int32_t prog_stage_bar_int;

int32_t get_var_prog_stage_bar_int() {
    return prog_stage_bar_int;
}

void set_var_prog_stage_bar_int(int32_t value) {
    prog_stage_bar_int = value;
}


char start_stop[20] = "--";

const char *get_var_start_stop() {
    return start_stop;
}

void set_var_start_stop(const char *value) {
    strncpy(start_stop, value, sizeof(start_stop) / sizeof(char));
    start_stop[sizeof(start_stop) / sizeof(char) - 1] = 0;
}


char face_away[20] = "--";

const char *get_var_face_away() {
    return face_away;
}

void set_var_face_away(const char *value) {
    strncpy(face_away, value, sizeof(face_away) / sizeof(char));
    face_away[sizeof(face_away) / sizeof(char) - 1] = 0;
}


bool start_stop_btn_checked_bool;

bool get_var_start_stop_btn_checked_bool() {
    return start_stop_btn_checked_bool;
}

void set_var_start_stop_btn_checked_bool(bool value) {
    start_stop_btn_checked_bool = value;
}


bool face_away_btn_checked_bool;

bool get_var_face_away_btn_checked_bool() {
    return face_away_btn_checked_bool;
}

void set_var_face_away_btn_checked_bool(bool value) {
    face_away_btn_checked_bool = value;
}


char prog_list[500] = { 0 };

const char *get_var_prog_list() {
    return prog_list;
}

void set_var_prog_list(const char *value) {
    strncpy(prog_list, value, sizeof(prog_list) / sizeof(char));
    prog_list[sizeof(prog_list) / sizeof(char) - 1] = 0;
}


char stage_list[100] = { 0 };

const char *get_var_stage_list() {
    return stage_list;
}

void set_var_stage_list(const char *value) {
    strncpy(stage_list, value, sizeof(stage_list) / sizeof(char));
    stage_list[sizeof(stage_list) / sizeof(char) - 1] = 0;
}


int32_t prog_list_sel_int;

int32_t get_var_prog_list_sel_int() {
    return prog_list_sel_int;
}

void set_var_prog_list_sel_int(int32_t value) {
    prog_list_sel_int = value;
}


int32_t stage_list_sel_int;

int32_t get_var_stage_list_sel_int() {
    return stage_list_sel_int;
}

void set_var_stage_list_sel_int(int32_t value) {
    stage_list_sel_int = value;
}
